public enum Genero {

    ACCION, DRAMA, COMEDIA, TERROR, ROMANCE, AVENTURA, CIENCIA_FICCION, DOCUMENTAL, ANIMACION, FANTASIA, MUSICAL, SUSPENSE, 
    BIOGRAFICA, HISTORICA, CRIMEN, COMEDIA_ROMANTICA , COMEDIA_AVENTURA, COMEDIA_DRAMA, COMEDIA_FANTASIA, COMEDIA_MUSICAL
}
